--- # Configuration Port
server:
  port: 8081

--- # Configuration Jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp

--- # Configuration Devtools
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

--- # Configuration MariaDb
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/boot
#    username: boot
#    password: boot
#    hikari:
#      maximum-pool-size: 100

--- # Configuration Oracle
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger
    hikari:
      maximum-pool-size: 10

--- # Configuration mybatis
mybatis:
  mapper-locations: classpath:sqlmapper/**/*.xml
# mybatis.configuration.map-underscore-to-camel-case=true

... # End