--- # Batch
spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

--- # Configuration MariaDb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/boot
    username: boot
    password: boot
  jpa:
    show-sql: true
